--- 
:logfile: "/var/log/rstatsd.log"
:loglevel: "INFO"
:cmds: 
- :cmd: "tail -F /var/log/nginx/www.access_log"
  :every: 100
  :regexes: 
  - :regex: '(?<http_method>[A-Z]+)\s.*?\sHTTP/1\.1"\s(?<http_code>\d+)\s'
    :metrics: 
    - "t1.aggregate"
    - "t1.individual"
    :statsd: true
  - :regex: '^.*$'
    :metrics: 
    - "t1.requests.aggregate"
    - "t1.requests.individual"
    :statsd: true
- :cmd: "tail -F /var/log/nginx/admin.access_log"
  :every: 500
  :regexes: 
  - :regex: '(?<http_method>[A-Z]+)\s.*?\sHTTP/1\.1"\s(?<http_code>\d+)\s'
    :metrics: 
    - "t2.aggregate"
    - "t2.individual"
    :statsd: true
- :cmd: "/usr/bin/mongostat 1"
  :regexes: 
#insert  query update delete getmore command flushes mapped  vsize    res faults locked % idx miss %     qr|qw   ar|aw  netIn netOut  conn               set repl       time 
  - :regex: '\s*(?<insert>\d+)\s*(?<query>\d+)\s*(?<update>\d+)\s*(?<delete>\d+)\s*(?<getmore>\d+)\s*(?<command>\d+)\s*(?<flushes>\d+)\s*.*?\s*.*?\s*.*?\s*(?<faults>\d+)'
    :use_value: true
    :metrics: 
    - "mongo"
:metric_prefix: "com.example.www."
:statsd: 
  :host: "graphite.example.com"
  :port: 8125
